services:

  nginx:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:rw

  php:
    build:
      context: docker
      dockerfile: php/Dockerfile
    volumes:
      - ./:/var/www/html:rw
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mariadb:10.6.9
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - "${DB_LOCAL_DIR_DATA}:/var/lib/mysql:rw"
      - "${DB_LOCAL_DIR_LOGS}:/var/log/mysql:rw"